name: MERN CI

on: 
  push:
    branches: [main]

jonbs: 
    deploy:
        run-on: ubuntu-latest

        steps:
          -name: Deploy via SHH
           uses: appleboy/ssh-action@v1
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                  cd devops-mern/
                  git pull origin main
                  sudo docker-compose down 
                  sudo docker-compose up --build -d